<template>
  <ArticleTemplate
    title="How to rename your device?"
    hero-image="/243A2909-0-1920x1080.jpg"
    date="2022-11-29"
    :related-articles="relatedArticles"
  >
    <h2>How to rename your devices in Webkey?</h2>

    <p>When you have a large number of devices to control, it is important to be able to identify them. With Webkey it is possible to rename your devices and even name device groups.</p>

    <p>This will allow you to personalize the overview of your devices.</p>

    <p>Normally, our app will attempt to identify the device based on the below factors:</p>

    <ul>
      <li>Network MAC address. If there are more than one interface, we will use a select list for this.</li>
      <li>Android Serial. This is a deprecated function on more recent Android versions.</li>
      <li>Additionally, there is a public ID (in uuid format). This is generated by Webkey and is unique for all devices.</li>
    </ul>

    <p>To name your device, go to your dashboard and click on the device you wish to rename.</p>

    <p>After clicking on the sandwich menu, you will see the following:</p>

    <img src="/images/articles/rename1.png" alt="Rename menu screenshot" style="max-width: 225px;" />

    <p>On the top of the next screen, you will see the default name of your device. Simply clicking on the edit, you will be able to rename your device.</p>

    <img src="/images/articles/rename2.png" alt="Edit interface screenshot" style="max-width: 512px;" />
  </ArticleTemplate>
</template>

<script setup>
import ArticleTemplate from '../../components/ArticleTemplate.vue'

const relatedArticles = [
  {
    id: 1,
    title: 'About location tracking',
    link: '/locationtracking',
    image: '/243A2909-0-1920x1080.jpg'
  },
  {
    id: 2,
    title: 'What is screen mirroring?',
    link: '/screen-mirroring-webkey',
    image: '/243A2909-0-1920x1080.jpg'
  }
]
</script>
